app_ui <- function(request = NULL) {
  shiny::fluidPage(
    shiny::tags$head(
      shiny::tags$title("SPI | Global Overview"),
      shiny::tags$style(shiny::HTML(
        paste(
          "* { box-sizing: border-box; }",
          "body { margin: 0; background: #f7f8fa; color: #17324d;",
          "font-family: 'Trebuchet MS', 'Segoe UI', sans-serif; }",
          ".spi-topbar { background: #062b4c; color: white; padding: 12px 3%;",
          "display: flex; justify-content: space-between; align-items: center; }",
          ".spi-brand-wrap { display: flex; align-items: center; gap: 12px; }",
          ".spi-brand-mark { display: flex; align-items: center; justify-content: center;",
          "width: 38px; height: 38px; border-radius: 50%; background: white; color: #062b4c;",
          "font-size: 12px; font-weight: 800; }",
          ".spi-brand { font-size: 17px; font-weight: 700; letter-spacing: -.01em; }",
          ".spi-nav { color: #a9bfd1; font-size: 12px; margin-left: 8px; }",
          ".spi-shell { max-width: 1360px; margin: 0 auto; padding: 32px 4% 54px; }",
          ".spi-kicker { color: #0b9ed0; font-size: 11px; font-weight: 700;",
          "text-transform: uppercase; letter-spacing: .12em; }",
          ".spi-title { margin: 5px 0 4px; font-size: 34px; color: #17324d; }",
          ".spi-intro { color: #60788d; max-width: 620px; margin: 0 0 24px; }",
          ".spi-controls { display: flex; justify-content: flex-end; margin-top: -50px;",
          "margin-bottom: 26px; }",
          ".spi-controls .form-group { margin: 0; min-width: 150px; }",
          ".spi-controls label { color: #60788d; font-size: 11px; text-transform: uppercase; }",
          ".spi-controls select { border: 1px solid #c9d8e1; border-radius: 3px;",
          "height: 38px; background: white; font-weight: 700; color: #17324d; }",
          ".spi-kpis { display: grid; grid-template-columns: repeat(5, 1fr); gap: 14px;",
          "margin-bottom: 18px; }",
          ".spi-card { background: white; border: 1px solid #e0e8ed; border-radius: 7px;",
          "box-shadow: 0 2px 8px rgba(23,50,77,.05); }",
          ".spi-kpi { padding: 18px 20px; border-top: 3px solid #0b9ed0; min-height: 118px; }",
          ".spi-label { color: #6b8090; text-transform: uppercase; font-size: 10px;",
          "font-weight: 700; letter-spacing: .05em; }",
          ".spi-value { color: #17324d; font-size: 31px; font-weight: 700; margin: 8px 0 3px; }",
          ".spi-note { color: #27a36a; font-size: 11px; }",
          ".spi-main-grid { display: grid; grid-template-columns: minmax(0, 1fr);",
          "gap: 18px; margin-bottom: 18px; }",
          ".spi-bottom-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 18px; }",
          ".spi-panel { padding: 20px; min-height: 290px; }",
          ".spi-panel h3 { font-size: 16px; margin: 0 0 3px; color: #17324d; }",
          ".spi-panel p { color: #7890a0; font-size: 11px; margin: 0 0 15px; }",
          ".spi-variation { margin-top: 16px; padding-top: 16px;",
          "border-top: 1px solid #d8e3e9; color: #7890a0; font-size: 11px; }",
          ".spi-variation-title { color: #60788d; font-size: 12px;",
          "margin-bottom: 8px; }",
          ".spi-map-panel { padding: 20px; margin-bottom: 18px; }",
          ".spi-map { min-height: 520px; background: #e3f2f8; border-radius: 4px;",
          "overflow: hidden; }",
          ".spi-map iframe { display: block; width: 100%; height: 520px; border: 0; }",
          ".spi-chart { width: 100%; height: 245px; }",
          ".spi-footer { margin-top: 24px; color: #7890a0; font-size: 11px; }",
          ".spi-tabs { border: 0; margin-top: 8px; }",
          ".spi-tabs > .nav-tabs { border-bottom: 1px solid #e1e6eb; margin: -32px -4% 30px;",
          "padding: 0 4%; background: white; }",
          ".spi-tabs > .nav-tabs > li > a { border: 0; color: #6c747c; font-size: 12px;",
          "font-weight: 700; padding: 15px 18px 13px; }",
          ".spi-tabs > .nav-tabs > li.active > a { color: #0b9ed0; background: transparent;",
          "border-bottom: 3px solid #0b9ed0; }",
          ".spi-explorer-page h1 { margin-bottom: 4px; }",
          ".spi-explorer-page .spi-intro { margin-bottom: 20px; }",
          ".spi-explorer-controls { display: grid; grid-template-columns: repeat(6, minmax(0, 1fr));",
          "gap: 12px; align-items: end; background: white; padding: 18px 16px 14px;",
          "border: 1px solid #e5e8ec; border-radius: 8px; box-shadow: 0 2px 7px rgba(23,50,77,.06);",
          "margin-bottom: 14px; }",
          ".spi-explorer-controls .form-group { margin: 0; min-width: 0; }",
          ".spi-explorer-controls label { color: #3e4d59; font-size: 11px; font-weight: 700;",
          "margin-bottom: 6px; }",
          ".spi-explorer-controls .form-control { height: 34px; border-color: #d7dde2;",
          "border-radius: 6px; box-shadow: none; color: #243746; font-size: 12px; }",
          ".spi-explorer-controls .btn { height: 34px; border-radius: 6px; font-size: 12px;",
          "padding: 6px 16px; }",
          ".spi-explorer-controls .btn-primary { background: #079bd3; border-color: #079bd3; }",
          ".spi-explorer-summary { display: flex; align-items: center; gap: 8px; color: #697680;",
          "font-size: 12px; margin: 0 0 10px; }",
          ".spi-explorer-summary > span { white-space: nowrap; }",
          ".spi-explorer-summary > span:not(:last-of-type)::after { content: '|'; margin-left: 8px; color: #b8c1c8; }",
          ".spi-explorer-summary .shiny-text-output { color: #344b5c; font-weight: 700; }",
          ".spi-explorer-status { color: #c45d37; margin-left: auto; }",
          ".spi-explorer-table { background: white; border: 1px solid #e5e8ec; border-radius: 8px;",
          "padding: 0 10px 8px; box-shadow: 0 2px 7px rgba(23,50,77,.04); }",
          ".spi-explorer-table .dataTables_wrapper { padding-top: 8px; }",
          ".spi-explorer-table table.dataTable thead th { background: #fbfbfc; color: #53616c;",
          "font-size: 11px; font-weight: 700; border-bottom: 1px solid #dfe5e9; }",
          ".spi-explorer-table table.dataTable tbody td { color: #344b5c; font-size: 12px;",
          "padding: 11px 8px; border-top: 1px solid #edf0f2; }",
          ".spi-explorer-table table.dataTable tbody tr:nth-child(even) { background: #f7fbfd; }",
          ".spi-score { display: inline-block; min-width: 42px; padding: 4px 9px;",
          "border-radius: 14px; background: #e5f6ed; color: #087b4d; font-weight: 700; text-align: center; }",
          "@media (max-width: 900px) { .spi-explorer-controls { grid-template-columns: repeat(2, minmax(0, 1fr)); }",
          ".spi-explorer-controls .btn { width: 100%; } }",
          "@media (max-width: 620px) { .spi-explorer-controls { grid-template-columns: 1fr; }",
          ".spi-explorer-summary { flex-wrap: wrap; } .spi-nav { display: none; } }",
          ".spi-placeholder { min-height: 430px; display: flex; align-items: center;",
          "justify-content: center; text-align: center; background: white; border: 1px solid #e0e8ed;",
          "border-radius: 7px; box-shadow: 0 2px 8px rgba(23,50,77,.05); }",
          ".spi-placeholder h2 { color: #17324d; font-size: 22px; margin: 0 0 8px; }",
          ".spi-placeholder p { color: #7890a0; font-size: 13px; margin: 0; }",
          "@media (max-width: 900px) { .spi-kpis, .spi-main-grid, .spi-bottom-grid { grid-template-columns: 1fr 1fr; } .spi-main-grid { grid-column: span 2; } .spi-controls { margin-top: 0; justify-content: flex-start; } }",
          "@media (max-width: 620px) { .spi-kpis, .spi-main-grid, .spi-bottom-grid { grid-template-columns: 1fr; } .spi-main-grid { grid-column: auto; } .spi-title { font-size: 28px; } }",
          sep = "\n"
        )
      ))
    ),
    shiny::div(class = "spi-topbar",
      shiny::div(class = "spi-brand-wrap",
        shiny::div(class = "spi-brand-mark", "WB"),
        shiny::div(class = "spi-brand", "Statistical Performance Indicators"),
        shiny::div(class = "spi-nav", "World Bank Group")
      ),
    ),
    shiny::div(class = "spi-shell",
      shiny::div(class = "spi-tabs",
        shiny::tabsetPanel(id = "main_nav", type = "tabs",
        shiny::tabPanel("Overview",
          shiny::div(class = "spi-kicker", "SPI dashboard"),
          shiny::h1(class = "spi-title", "Global Overview"),
          shiny::p(class = "spi-intro", "How well are national statistical systems performing worldwide? Explore SPI scores across economies and over time."),
          shiny::div(class = "spi-kpis",
        shiny::div(class = "spi-card spi-kpi", shiny::div(class = "spi-label", "Countries covered"), shiny::div(class = "spi-value", shiny::textOutput("kpi_countries", inline = TRUE)), shiny::div(class = "spi-note", "All available economies")),
        shiny::div(class = "spi-card spi-kpi", shiny::div(class = "spi-label", "Latest data year"), shiny::div(class = "spi-value", shiny::textOutput("kpi_years", inline = TRUE)), shiny::div(class = "spi-note", "Most recent valid SPI data")),
        shiny::div(class = "spi-card spi-kpi", shiny::div(class = "spi-label", "Global average score"), shiny::div(class = "spi-value", shiny::textOutput("kpi_average", inline = TRUE)), shiny::div(class = "spi-note", "Latest available year")),
          shiny::div(class = "spi-card spi-kpi", shiny::div(class = "spi-label", "Years with valid data"), shiny::div(class = "spi-value", shiny::textOutput("kpi_year_count", inline = TRUE)), shiny::div(class = "spi-note", shiny::textOutput("kpi_year_range", inline = TRUE))),
          shiny::div(class = "spi-card spi-kpi", shiny::div(class = "spi-label", "Median improvement since 2016"), shiny::div(class = "spi-value", shiny::textOutput("kpi_improvement", inline = TRUE)), shiny::div(class = "spi-note", "Points gained (median country)"))
          ),
          shiny::div(class = "spi-card spi-map-panel",
            shiny::h3("SPI Scores by Country"),
            shiny::p("Global SPI scores for the latest available year."),
            shiny::div(class = "spi-map", shiny::uiOutput("overview_flourish_map"))
          ),
          shiny::div(class = "spi-main-grid",
        shiny::div(class = "spi-card spi-panel", shiny::h3("Score Distribution"), shiny::p("Countries grouped by SPI score."), shiny::plotOutput("overview_distribution", height = "235px"))
          ),
          shiny::div(class = "spi-bottom-grid",
        shiny::div(class = "spi-card spi-panel", shiny::h3("Average SPI by Region"), shiny::p("Official aggregate scores for the latest available year."), shiny::plotOutput("overview_regions", height = "220px")),
        shiny::div(class = "spi-card spi-panel", shiny::h3("Average SPI by Income Group"), shiny::p("Country-level averages for the latest available year."), shiny::plotOutput("overview_groups", height = "220px"), shiny::div(class = "spi-variation", shiny::div(class = "spi-variation-title", "Within-group variation (IQR)"), shiny::textOutput("overview_income_variation", inline = FALSE)))
          ),
          shiny::div(class = "spi-footer", "Source: World Bank Statistical Performance Indicators (SPI). Data provider: ", shiny::textOutput("footer_provider", inline = TRUE))
        ),
        shiny::tabPanel("Country Explorer",
          shiny::div(class = "spi-explorer-page",
            shiny::h1(class = "spi-title", "Country Explorer"),
            shiny::p(class = "spi-intro", "Browse and filter SPI scores across all countries. Select a row to explore the full country profile."),
            country_explorer_ui("country_explorer")
          )
        ),
        shiny::tabPanel("Country Profile",
          shiny::div(class = "spi-placeholder", shiny::div(shiny::h2("Country Profile"), shiny::p("Detailed country profiles will be available in a future iteration.")))
        ),
        shiny::tabPanel("Compare Countries",
          shiny::div(class = "spi-placeholder", shiny::div(shiny::h2("Compare Countries"), shiny::p("Country comparison tools will be available in a future iteration.")))
        ),
        shiny::tabPanel("Trends & Progress",
          shiny::div(class = "spi-card spi-panel", shiny::h2("Trends & Progress"), shiny::p("Regional trends from the official spiR visualization functions."), shiny::plotOutput("overview_region_history", height = "520px"))),
        shiny::tabPanel("Explore by Pillar",
          shiny::div(class = "spi-placeholder", shiny::div(shiny::h2("Explore by Pillar"), shiny::p("Pillar and dimension exploration will be available in a future iteration.")))
        ),
        shiny::tabPanel("Data & Downloads",
          shiny::div(class = "spi-placeholder", shiny::div(shiny::h2("Data & Downloads"), shiny::p("Data access tools will be available in a future iteration.")))
        )
      )
      )
    )
  )
}
